global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: mini-ifood-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app:8080

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121

